language: perl
perl:
  - "dev"
  - "5.24"
  - "5.22"
  - "5.16"
  - "5.10"
env:
  global:
    - "AUTHOR_TESTING=1"
    - "RELEASE_TESTING=1"
before_install:
  - "git config --global user.email 'test@example.com'"
  - "git config --global user.name 'Test User'"
  - "git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers"
  - "source ~/travis-perl-helpers/init"
  - "build-perl"
  - "perl -V"
  - "build-dist"
  - "cd $BUILD_DIR"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps . || { cat ~/.cpanm/build.log ; false ; }"
script:
  - "perl Makefile.PL && make test"
