language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.16"
install:
  - "cpanm -n JSON::PP Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }"
  - "dzil authordeps --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }"
  - "dzil listdeps --author --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }"
script:
  - "dzil test --author --release --keep"
